# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: multizoneVLANnew
# label used for menu selection
label: VLAN_based multizone baseline config
description: adds the base elements like untrust zone and logging profile

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - mssp
    - multizone

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: INTF_UNTRUST
    description: Untrust Interface
    default: ethernet1/1
    type_hint: text
  - name: ZONE_UNTRUST
    description: Untrust zone
    default: untrust
    type_hint: text
  - name: INTF_TRUST
    description: trust Interface
    default: ethernet1/2
    type_hint: text
  - name: SYSLOG_SERVER
    description: Syslog Server IP
    default: 192.0.6.1
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: shared_log_settings
    xpath: /config/shared/log-settings
    file: shared_log_settings.xml
  - name: log_settings_profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles
    file: log_settings_profiles.xml
  - name: interface
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface
    file: interface.xml
  - name: virtual_router
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: virtual_router.xml
  - name: zone_protection_profile
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile
    file: zone_protection_profile.xml
  - name: zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
    file: zone.xml
# ---------------------------------------------------------------------
# end of snippets section