# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: multizoneVLANbase
# label used for menu selection
label: VLAN_based multizone security policies for new customer
description: Creates vlan interface along with associated zone and security policies

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - mssp
    - multizone

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: customer_ID
    description: Customer identifier (max 8 characters)
    default: Cust1234
    type_hint: text
  - name: INTF_TRUST
    description: trust interface
    default: ethernet1/2
    type_hint: text
  - name: vlan_tag
    description: vlan tag number
    default: 100
    type_hint: text
  - name: vlan_ip
    description: vlan IP address
    default: 192.0.7.1/30
    type_hint: text
  - name: tag_color
    description: Tag color
    default: red
    type_hint: dropdown
    dd_list:
      - key: blue
        value: color3
      - key: green
        value: color2
      - key: orange
        value: color6
      - key: red
        value: color1
  - name: INTF_UNTRUST
    description: untrust interface
    default: ethernet1/1
    type_hint: text
  - name: ZONE_UNTRUST
    description: untrust zone
    default: untrust
    type_hint: text
  - name: SINKHOLE_IPV4
    description: sinkhole address IPv4
    default: 72.5.65.111
    type_hint: ip_address
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    default: 2600:5200::1
    type_hint: ip_address

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: profiles_virus
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus
    file: profiles_virus.xml
  - name: profiles_spyware
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/spyware
    file: profiles_spyware.xml
  - name: profiles_vulnerability
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/vulnerability
    file: profiles_vulnerability.xml
  - name: profiles_file_blocking
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/file-blocking
    file: profiles_file_blocking.xml
  - name: profiles_url_filtering
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering
    file: profiles_url_filtering.xml
  - name: profiles_wildfire_analysis
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/wildfire-analysis
    file: profiles_wildfire_analysis.xml
  - name: profile_group
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profile-group
    file: profile_group.xml
  - name: network_profiles-network-profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/profiles
    file: network_profiles.xml
  - name: interface
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface
    file: interface.xml
  - name: virtual_router
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: virtual_router.xml
  - name: zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
    file: zone.xml
  - name: nat-source-nat-to-untrust
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/nat
    file: source_nat_to_untrust.xml
  - name: profile_group_unknown_url
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profile-group
    file: profile_group_unknown_url.xml
  - name: security_rules-security-rules-gold
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security
    file: security_rules_gold.xml
# ---------------------------------------------------------------------
# end of snippets section